default:
  navigation:
    - title: Fruits
      subtitle: Categories
      url: /t/fruits
      items:
        - :title: Pomes
          :url: /t/fruits/pomes
        - :title: Drupes
          :url: /t/fruits/drupes
        - :title: Berries
          :url: /t/fruits/berries
        - :title: Melons
          :url: /t/fruits/melons
        - :title: Citrus
          :url: /t/fruits/citrus
        - :title: Tropical
          :url: /t/fruits/tropical
      promo_banners:
        - subtitle: New collection
          title: Season Special
          url: /t/new-collection/season-special
          image: 'meganav/promo_banner_left-first-category.jpg'
        - subtitle: Special Offers
          title: Get up to 30% off
          url: /t/special-offers/30-off
          image: 'meganav/promo_banner_right-first-category.jpg'
    - title: Vegetables
      subtitle: Categories
      url: /t/vegetables
      items:
        - :title: Bulbs
          :url: /t/vegetables/bulbs
        - :title: Root and Tubers
          :url: /t/vegetables/root-and-tubers
        - :title: Stem
          :url: /t/vegetables/stem
        - :title: Leaf
          :url: /t/vegetables/leaf
      promo_banners:
        - subtitle: New collection
          title: Season Special
          url: /t/new-collection/season-special
          image: 'meganav/promo_banner_left-second-category.jpg'
        - subtitle: Special Offers
          title: Get up to 30% off
          url: /t/special-offers/30-off
          image: 'meganav/promo_banner_right-second-category.jpg'
    - title: Exotic Vegetables
      subtitle: Categories
      url: /t/exotic-vegetables
      items:
        - :title: Broccoli
          :url: /t/exotic-vegetables/broccoli
        - :title: Baby corn
          :url: /t/exotic-vegetables/baby-corn
        - :title: Bell peppers
          :url: /t/exotic-vegetables/bell-peppers
          :title: Celery
          :url: /t/exotic-vegetables/celery
      promo_banners:
        - subtitle: New collection
          title: Season Special
          url: /t/new-collection/season-special
          image: 'meganav/promo_banner_left-third-category.jpg'
        - subtitle: Special Offers
          title: Get up to 30% off
          url: /t/special-offers/30-off
          image: 'meganav/promo_banner_right-third-category.jpg'
